name: hw2
version: 0.1.0.0
github: "githubuser/hw2"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2023 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hw2#readme>

dependencies:
  - base >= 4.7 && < 5
  - HUnit
  - hspec
  - hedgehog
  - tasty
  - tasty-smallcheck
  - tasty-quickcheck
  - tasty-hunit
  - tasty-hspec
  - tasty-hedgehog
  - QuickCheck
  - containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  hw2-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hw2

tests:
  task-1:
    main: Spec.hs
    source-dirs: test/T1
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
#      - -i -isrc -itest
    dependencies:
      - hw2
      - HUnit
  task-2:
    main: Spec.hs
    source-dirs: test/T2
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
#      - -i -isrc -itest
    dependencies:
      - hw2
      - HUnit
  task-3:
    main: Spec.hs
    source-dirs: test/T3
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
#      - -i -isrc -itest
    dependencies:
      - hw2
      - HUnit
  task-4:
    main: Spec.hs
    source-dirs: test/T4
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
#      - -i -isrc -itest
    dependencies:
      - hw2
      - HUnit
